[project]
name = "counts3-alpha"
version = "0.2.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Ronivaldo Silva", email = "Ronivaldo.alpha@gmail.com" }
]
dependencies = [
    "flet=0.85.0",
    "fastapi",
    "uvicorn[standard]"
]

[dependency-groups]
dev = [
    "flet-cli=0.85.0",
    "flet-desktop=0.85.0",
    "flet-web=0.85.0",
    "SQLAlchemy",
    "psycopg2-binary",
    "python-dotenv",
    "requests"
]

[tool.flet]
org = "com.alphaformate"
product = "alpha-counts3"
company = "AlphaFormate"
copyright = "Copyright (C) 2026 by AlphaFormate"

[tool.flet.app]
path = "src"
module = "main.py"

[tool.flet.web]
